import React from "react";

interface DiagramViewerProps {
  svgCode: string | null;
  title: string;
}

export default function DiagramViewer({ svgCode, title }: DiagramViewerProps) {
  if (!svgCode) {
    return (
      <div className="flex items-center justify-center p-8 bg-slate-50 border border-slate-200 rounded-xl">
        <p className="text-slate-400 text-sm">No diagram available for this lesson.</p>
      </div>
    );
  }

  // Clean the SVG code generated by Gemini
  const cleanSvg = (rawCode: string): string => {
    let clean = rawCode.trim();

    // Remove markdown code blocks if present
    if (clean.includes("```xml")) {
      clean = clean.split("```xml")[1].split("```")[0];
    } else if (clean.includes("```html")) {
      clean = clean.split("```html")[1].split("```")[0];
    } else if (clean.includes("```svg")) {
      clean = clean.split("```svg")[1].split("```")[0];
    } else if (clean.includes("```")) {
      clean = clean.split("```")[1].split("```")[0];
    }

    // Try to find <svg and </svg>
    const startIndex = clean.indexOf("<svg");
    const endIndex = clean.lastIndexOf("</svg>");

    if (startIndex !== -1 && endIndex !== -1) {
      clean = clean.substring(startIndex, endIndex + 6);
    }

    return clean;
  };

  const processedSvg = cleanSvg(svgCode);

  return (
    <div className="bg-white border border-slate-200 rounded-2xl overflow-hidden shadow-sm">
      <div className="bg-slate-50 px-6 py-4 border-b border-slate-200 flex items-center justify-between">
        <h4 className="text-sm font-semibold text-slate-700">Learning Aid: Visual Diagram</h4>
        <span className="text-xs bg-indigo-50 text-indigo-600 px-2.5 py-1 rounded-full font-medium">
          {title}
        </span>
      </div>
      <div className="p-6 flex justify-center bg-slate-50/50">
        <div
          className="w-full max-w-lg aspect-video flex items-center justify-center svg-container [&>svg]:w-full [&>svg]:h-auto [&>svg]:max-h-full"
          dangerouslySetInnerHTML={{ __html: processedSvg }}
        />
      </div>
    </div>
  );
}
